/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import forme.kampanja.FormaIzmeniKampanju;
import forme.kampanja.FormaKreirajKampanju;
import forme.zaposleni.FormaKreirajZaposlenog;
import forme.partner.FormaObrisiPartnera;
import forme.partner.FormaIzmeniPartnera;
import forme.partner.FormaKreirajPartnera;
import forme.zaposleni.FormaIzmeniZaposlenog;
import forme.zaposleni.FormaObrisiZaposlenog;


/**
 *
 * @author Danilo
 */
public class MainForma extends javax.swing.JFrame {

    /**
     * Creates new form MainForma
     */
    public MainForma() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miKreirajPartnera = new javax.swing.JMenuItem();
        miIzmeniPartner = new javax.swing.JMenuItem();
        miObrisiPartnera = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miKreirajKampanju = new javax.swing.JMenuItem();
        miIzmeniKampanju = new javax.swing.JMenuItem();
        miObrisiKampanje = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miKreirajZaposlenog = new javax.swing.JMenuItem();
        miIzmeniZaposlenog = new javax.swing.JMenuItem();
        miObrisiZaposleni = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Softver za vodjenje marketing agencije");

        jMenu1.setText("Partner");

        miKreirajPartnera.setText("Kreiraj");
        miKreirajPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKreirajPartneraActionPerformed(evt);
            }
        });
        jMenu1.add(miKreirajPartnera);

        miIzmeniPartner.setText("Izmeni");
        miIzmeniPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miIzmeniPartnerActionPerformed(evt);
            }
        });
        jMenu1.add(miIzmeniPartner);

        miObrisiPartnera.setText("Obrisi");
        miObrisiPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miObrisiPartneraActionPerformed(evt);
            }
        });
        jMenu1.add(miObrisiPartnera);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Kampanja");

        miKreirajKampanju.setText("Kreiraj");
        miKreirajKampanju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKreirajKampanjuActionPerformed(evt);
            }
        });
        jMenu2.add(miKreirajKampanju);

        miIzmeniKampanju.setText("Izmeni");
        miIzmeniKampanju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miIzmeniKampanjuActionPerformed(evt);
            }
        });
        jMenu2.add(miIzmeniKampanju);

        miObrisiKampanje.setText("Obrisi");
        jMenu2.add(miObrisiKampanje);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Zaposleni");

        miKreirajZaposlenog.setText("Kreiraj");
        miKreirajZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKreirajZaposlenogActionPerformed(evt);
            }
        });
        jMenu3.add(miKreirajZaposlenog);

        miIzmeniZaposlenog.setText("Izmeni");
        miIzmeniZaposlenog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miIzmeniZaposlenogActionPerformed(evt);
            }
        });
        jMenu3.add(miIzmeniZaposlenog);

        miObrisiZaposleni.setText("Obrisi");
        miObrisiZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miObrisiZaposleniActionPerformed(evt);
            }
        });
        jMenu3.add(miObrisiZaposleni);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miKreirajPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajPartneraActionPerformed
        FormaKreirajPartnera fkp = new FormaKreirajPartnera();
        fkp.setVisible(true);
    }//GEN-LAST:event_miKreirajPartneraActionPerformed

    private void miIzmeniPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIzmeniPartnerActionPerformed
        FormaIzmeniPartnera fip = new FormaIzmeniPartnera();
        fip.setVisible(true);
    }//GEN-LAST:event_miIzmeniPartnerActionPerformed

    private void miObrisiPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miObrisiPartneraActionPerformed
       FormaObrisiPartnera fop =  new FormaObrisiPartnera();
       fop.setVisible(true);
    }//GEN-LAST:event_miObrisiPartneraActionPerformed

    private void miKreirajZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajZaposlenogActionPerformed
        FormaKreirajZaposlenog fkz = new FormaKreirajZaposlenog();
        fkz.setVisible(true);
    }//GEN-LAST:event_miKreirajZaposlenogActionPerformed

    private void miIzmeniZaposlenogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIzmeniZaposlenogActionPerformed
        FormaIzmeniZaposlenog fiz = new FormaIzmeniZaposlenog();
        fiz.setVisible(true);
    }//GEN-LAST:event_miIzmeniZaposlenogActionPerformed

    private void miObrisiZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miObrisiZaposleniActionPerformed
        FormaObrisiZaposlenog foz = new FormaObrisiZaposlenog();
        foz.setVisible(true);
    }//GEN-LAST:event_miObrisiZaposleniActionPerformed

    private void miKreirajKampanjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajKampanjuActionPerformed
        FormaKreirajKampanju fkk = new FormaKreirajKampanju();
        fkk.setVisible(true);
    }//GEN-LAST:event_miKreirajKampanjuActionPerformed

    private void miIzmeniKampanjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miIzmeniKampanjuActionPerformed
        FormaIzmeniKampanju fik = new FormaIzmeniKampanju();
        fik.setVisible(true);
    }//GEN-LAST:event_miIzmeniKampanjuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miIzmeniKampanju;
    private javax.swing.JMenuItem miIzmeniPartner;
    private javax.swing.JMenuItem miIzmeniZaposlenog;
    private javax.swing.JMenuItem miKreirajKampanju;
    private javax.swing.JMenuItem miKreirajPartnera;
    private javax.swing.JMenuItem miKreirajZaposlenog;
    private javax.swing.JMenuItem miObrisiKampanje;
    private javax.swing.JMenuItem miObrisiPartnera;
    private javax.swing.JMenuItem miObrisiZaposleni;
    // End of variables declaration//GEN-END:variables

}
