/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme.kampanja;

import domen.Kampanja;
import domen.Partner;
import domen.Zadatak;
import domen.Zaposleni;
import forme.modeli.tabela.ModelTabeleKampanja;
import forme.modeli.tabela.ModelTabeleZadatak;
import forme.zadatak.FormaPrikaziZadatak;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import komunikacija.Odgovor;
import komunikacija.VrstaOdgovora;
import konstante.Konstante;
import kontroler.KontrolerKIKampanja;

/**
 *
 * @author Danilo
 */
public class FormaObrisiKampanju extends javax.swing.JFrame {
    Kampanja izabranaKampanja;

    /**
     * Creates new form FormaKreirajKampanju
     */
    public FormaObrisiKampanju() {
        initComponents();
        setLocationRelativeTo(null);
        postaviModelTabeleKampanja();
        postaviModelTabeleZadatak();
        popuniSveKampanje();
        popuniPartnere();
        popuniZaposlene();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGlavniOdgovorni = new javax.swing.JLabel();
        lblParnter = new javax.swing.JLabel();
        lblNaziv = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        txtDatumPocetka = new javax.swing.JTextField();
        txtDatumZavrsetka = new javax.swing.JTextField();
        cmbPartner = new javax.swing.JComboBox();
        lblDatumPocetka = new javax.swing.JLabel();
        cmbGlavniOdgovorni = new javax.swing.JComboBox();
        lblDatumZavrsetka = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblZadaci = new javax.swing.JTable();
        btnPrikaziZadatak = new javax.swing.JButton();
        btnObrisiKampanju = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKampanje = new javax.swing.JTable();
        txtVrednostPretrage = new javax.swing.JTextField();
        btnPretraziKampanje = new javax.swing.JButton();
        btnUcitajKampanju = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Obriši kampanju");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Podaci o kampanji"));

        lblGlavniOdgovorni.setText("Glavni odgvorni:");

        lblParnter.setText("Za partnera:");

        lblNaziv.setText("Naziv:");

        txtNaziv.setEditable(false);
        txtNaziv.setFocusable(false);

        txtDatumPocetka.setEditable(false);
        txtDatumPocetka.setFocusable(false);

        txtDatumZavrsetka.setEditable(false);
        txtDatumZavrsetka.setFocusable(false);

        cmbPartner.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPartner.setEnabled(false);
        cmbPartner.setFocusable(false);

        lblDatumPocetka.setText("Datum početka:");

        cmbGlavniOdgovorni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGlavniOdgovorni.setEnabled(false);
        cmbGlavniOdgovorni.setFocusable(false);
        cmbGlavniOdgovorni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGlavniOdgovorniActionPerformed(evt);
            }
        });

        lblDatumZavrsetka.setText("Datum završetka:");

        tblZadaci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblZadaci);

        btnPrikaziZadatak.setText("Prikaži zadatak");
        btnPrikaziZadatak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziZadatakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDatumZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGlavniOdgovorni, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblParnter, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatumZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbGlavniOdgovorni, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPrikaziZadatak)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblParnter, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNaziv)
                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDatumPocetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDatumZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDatumZavrsetka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGlavniOdgovorni, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbGlavniOdgovorni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrikaziZadatak)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnObrisiKampanju.setText("Obriši kampanju");
        btnObrisiKampanju.setEnabled(false);
        btnObrisiKampanju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiKampanjuActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Izaberi kampanju"));

        tblKampanje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblKampanje);

        btnPretraziKampanje.setText("Pretraži kampanje");
        btnPretraziKampanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziKampanjeActionPerformed(evt);
            }
        });

        btnUcitajKampanju.setText("Učitaj kampanju");
        btnUcitajKampanju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcitajKampanjuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtVrednostPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPretraziKampanje))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(379, 379, 379)
                        .addComponent(btnUcitajKampanju, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVrednostPretrage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziKampanje))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUcitajKampanju, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(btnObrisiKampanju, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnObrisiKampanju, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrikaziZadatakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziZadatakActionPerformed
        {
            ModelTabeleZadatak mtz = (ModelTabeleZadatak) tblZadaci.getModel();
            int izabraniRed = tblZadaci.getSelectedRow();
            if (izabraniRed != -1) {
                Zadatak zadatakZaPrikaz = mtz.vratiZadatak(izabraniRed);
                FormaPrikaziZadatak fpz = new FormaPrikaziZadatak(this, rootPaneCheckingEnabled, zadatakZaPrikaz);
                fpz.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Morate izabrati zadatak iz tabele.", Konstante.PORUKA_NEUSPESNO, JOptionPane.ERROR_MESSAGE);
        }        }    }//GEN-LAST:event_btnPrikaziZadatakActionPerformed

    private void btnObrisiKampanjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiKampanjuActionPerformed
        Kampanja kampanja = izabranaKampanja;

        Odgovor odgovor = KontrolerKIKampanja.getInstance().obrisiKampanju(kampanja);
        if (odgovor != null && odgovor.getVrstaOdgovora() == VrstaOdgovora.USPESNO) {
            JOptionPane.showMessageDialog(this, odgovor.getPoruka(), Konstante.PORUKA_USPESNO, JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da obriše kampanju.", Konstante.PORUKA_NEUSPESNO, JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_btnObrisiKampanjuActionPerformed

    private void btnUcitajKampanjuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcitajKampanjuActionPerformed
        int izabraniRed = tblKampanje.getSelectedRow();
        if (izabraniRed == -1) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita kampanju.", konstante.Konstante.PORUKA_NEUSPESNO, JOptionPane.ERROR_MESSAGE);
        } else {
            ModelTabeleKampanja mtk = (ModelTabeleKampanja) tblKampanje.getModel();
            izabranaKampanja = mtk.vratiKampanju(izabraniRed);
            popuniPodatkeKampanja(izabranaKampanja);
            JOptionPane.showMessageDialog(this, "Sistem je učitao kampanju.", konstante.Konstante.PORUKA_USPESNO, JOptionPane.INFORMATION_MESSAGE);
            btnObrisiKampanju.setEnabled(true);
        }
    }//GEN-LAST:event_btnUcitajKampanjuActionPerformed

    private void cmbGlavniOdgovorniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGlavniOdgovorniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGlavniOdgovorniActionPerformed

    private void btnPretraziKampanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziKampanjeActionPerformed
        String uslov = txtVrednostPretrage.getText();
        ArrayList<Kampanja> listaKampanjaPretraga = kontroler.KontrolerKIKampanja.getInstance().vratiKampanjeSaUslovom(uslov);
        if (listaKampanjaPretraga != null && !listaKampanjaPretraga.isEmpty()) {
            ModelTabeleKampanja mtk = (ModelTabeleKampanja) tblKampanje.getModel();
            mtk.setLista(listaKampanjaPretraga);
            JOptionPane.showMessageDialog(this, "Sistem je našao kampanje po zadatoj vrednosti.", Konstante.PORUKA_USPESNO, JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe kampanje po zadatoj vrednosti", Konstante.PORUKA_NEUSPESNO, JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }//GEN-LAST:event_btnPretraziKampanjeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnObrisiKampanju;
    private javax.swing.JButton btnPretraziKampanje;
    private javax.swing.JButton btnPrikaziZadatak;
    private javax.swing.JButton btnUcitajKampanju;
    private javax.swing.JComboBox cmbGlavniOdgovorni;
    private javax.swing.JComboBox cmbPartner;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDatumPocetka;
    private javax.swing.JLabel lblDatumZavrsetka;
    private javax.swing.JLabel lblGlavniOdgovorni;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblParnter;
    private javax.swing.JTable tblKampanje;
    private javax.swing.JTable tblZadaci;
    private javax.swing.JTextField txtDatumPocetka;
    private javax.swing.JTextField txtDatumZavrsetka;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtVrednostPretrage;
    // End of variables declaration//GEN-END:variables

    private void popuniPartnere() {
        cmbPartner.removeAllItems();
        ArrayList<Partner> listaSvihPartnera = kontroler.KontrolerKIPartner.getInstance().vratiSvePartnere();
        if (listaSvihPartnera != null && !listaSvihPartnera.isEmpty()) {
            for (Partner partner : listaSvihPartnera) {
                cmbPartner.addItem(partner);
            }
            cmbPartner.setSelectedItem(null);
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može ucita partnere", Konstante.PORUKA_NEUSPESNO, JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }

    private void popuniZaposlene() {
        cmbGlavniOdgovorni.removeAllItems();
        ArrayList<Zaposleni> listaSvihZaposlnih = kontroler.KontorlerKIZaposleni.getInstance().vratiSveZaposlene();
        if (listaSvihZaposlnih != null && !listaSvihZaposlnih.isEmpty()) {
            for (Zaposleni zaposleni : listaSvihZaposlnih) {
                cmbGlavniOdgovorni.addItem(zaposleni);
            }
            cmbGlavniOdgovorni.setSelectedItem(null);
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može ucita zaposlene", Konstante.PORUKA_NEUSPESNO, JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }

    private void postaviModelTabeleZadatak() {
        ModelTabeleZadatak mtz = new ModelTabeleZadatak();
        tblZadaci.setModel(mtz);
    }

    private void postaviModelTabeleKampanja() {
        ModelTabeleKampanja mtk = new ModelTabeleKampanja();
        tblKampanje.setModel(mtk);
    }

    private void popuniSveKampanje() {
        ArrayList<Kampanja> listaKampanja = KontrolerKIKampanja.getInstance().vratiSveKampanje();
        ModelTabeleKampanja mtk = (ModelTabeleKampanja) tblKampanje.getModel();
        if (listaKampanja != null && !listaKampanja.isEmpty()) {
            mtk.setLista(listaKampanja);
        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne može da vrati sve kampanje", Konstante.PORUKA_NEUSPESNO, JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }

    private void popuniPodatkeKampanja(Kampanja izabranaKampanja) {
        cmbPartner.setSelectedItem(izabranaKampanja.getPartner());
        txtNaziv.setText(izabranaKampanja.getNaziv());
        SimpleDateFormat sdf = Konstante.SIMPLE_DATE_FORMAT;
        txtDatumPocetka.setText(sdf.format(izabranaKampanja.getDatumPocetka()));
        txtDatumZavrsetka.setText(sdf.format(izabranaKampanja.getDatumZavrsetka()));
        cmbGlavniOdgovorni.setSelectedItem(izabranaKampanja.getOdgovorniZaposleni());
        ModelTabeleZadatak mtz = (ModelTabeleZadatak) tblZadaci.getModel();
        mtz.setLista((ArrayList<Zadatak>) izabranaKampanja.getZadaci());
    }
}
